import Link from 'next/link';
import { Check, CheckCircle2, ShieldCheck, Download, ArrowRight, BarChart3, FileText } from 'lucide-react';
import StoreCTA from './StoreCTA';
import { STORE_EN_PRODUCTS, type StoreProductId } from '@/lib/store/catalog';
import { productDetailsEN } from '@/lib/store/product-details-en';
import { storePath } from '@/lib/i18n';

export const primaryButton = 'inline-flex items-center justify-center gap-2 rounded-full bg-[#0683C9] px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-sky-900/10 transition hover:bg-sky-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4';
const section = 'mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-20';

export function EnglishHeader() {
  return <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-8">
    <Link href="/en" className="text-2xl font-black tracking-tight text-[#0683C9]">TalentiQues</Link>
    <nav aria-label="Main navigation" className="flex flex-wrap gap-4 text-sm font-semibold text-slate-600"><Link href="/en/tools">Tools</Link><Link href="/en/resources">Resources</Link><Link href="/en/coaching">Coaching</Link><Link href="/en#contact">Contact</Link></nav>
  </div></header>;
}
export function EnglishFooter() {
  return <footer className="bg-[#0F172A] text-slate-300"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-12 sm:grid-cols-2 sm:px-8"><div><Link href="/en" className="text-2xl font-black text-white">TalentiQues</Link><p className="mt-3 max-w-md text-sm leading-6">Practical career systems. A clearer application, an organised search and tools you can keep using.</p><a href="mailto:talentiques@gmail.com" className="mt-4 inline-block text-sm text-sky-300">talentiques@gmail.com</a></div><nav aria-label="Footer" className="grid grid-cols-2 gap-3 text-sm"><Link href="/en/tools">Career tools</Link><Link href="/en/resources">Resources</Link><Link href="/en/blog">Career insights</Link><Link href="/en/careers">Careers</Link><Link href="/en/privacy">Privacy policy</Link><Link href="/en/terms">Terms and conditions</Link><Link href="/en/legal">Legal information</Link></nav></div><p className="border-t border-white/10 px-5 py-6 text-center text-xs">© {new Date().getFullYear()} TalentiQues. All rights reserved.</p></footer>;
}
export function TrustStrip() {
  return <div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{['One-time payment', 'No subscription', 'Instant access after payment', 'English resources'].map(text => <div key={text} className="flex items-center gap-2 rounded-2xl border border-sky-100 bg-white p-4 text-xs font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 shrink-0 text-[#0683C9]" />{text}</div>)}</div>;
}
export function EnglishProductVisual({ id }: { id: StoreProductId }) {
  return <div className="rounded-[32px] border border-sky-200 bg-gradient-to-br from-sky-50 via-white to-indigo-50 p-5 shadow-xl shadow-sky-950/5 sm:p-8" aria-label={`${STORE_EN_PRODUCTS[id].name} illustrative preview`}>
    <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0683C9]">Your career workspace</p>
    <div className="mt-5 flex items-center gap-3"><div className="rounded-xl bg-[#0683C9] p-3 text-white">{id === 'ats' ? <FileText /> : <BarChart3 />}</div><h2 className="text-xl font-black">{STORE_EN_PRODUCTS[id].name}</h2></div>
    {id !== 'ats' && <div className="mt-6 rounded-2xl border border-slate-100 bg-white p-4"><div className="grid grid-cols-3 gap-2">{['Opportunities', 'Follow-ups', 'Interviews'].map((label, i) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-black text-[#0F172A]">{[12, 4, 2][i]}</p><p className="mt-1 text-[10px] text-slate-500">{label}</p></div>)}</div><div className="mt-5 space-y-3">{['Prioritise your next role', 'Prepare your application', 'Follow up with confidence'].map((label, i) => <div key={label} className="flex items-center gap-3 text-xs text-slate-600"><span className="rounded-full bg-sky-50 px-2 py-1 text-sky-700">0{i + 1}</span>{label}</div>)}</div></div>}
    {id !== 'tracker' && <div className="mt-5 rounded-2xl border border-slate-100 bg-white p-5"><p className="font-bold">Your name · Your next role</p><p className="mt-2 text-xs text-slate-500">Professional summary · Experience · Skills</p><div className="mt-4 space-y-2" aria-hidden="true">{['w-full', 'w-5/6', 'w-full', 'w-3/4'].map((width, i) => <div key={i} className={`${width} h-2 rounded bg-slate-100`} />)}</div><p className="mt-4 text-xs font-semibold text-[#0683C9]">7 templates + resume and LinkedIn guides</p></div>}
    <p className="mt-4 text-[11px] text-slate-500">Illustrative preview. Example data only.</p>
  </div>;
}
export function ProductCards() {
  return <div className="grid gap-5 lg:grid-cols-3">{(['tracker', 'bundle', 'ats'] as const).map(id => { const p = STORE_EN_PRODUCTS[id]; return <article key={id} className={`flex flex-col rounded-[28px] border bg-white p-6 ${id === 'bundle' ? 'border-[#0683C9] shadow-xl shadow-sky-900/10' : 'border-slate-200'}`}><p className="text-xs font-bold uppercase tracking-widest text-[#0683C9]">{id === 'bundle' ? 'The complete system' : 'Build your foundation'}</p><h2 className="mt-4 text-2xl font-black">{p.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{p.description}</p><div className="my-6"><span className="text-4xl font-black">{p.displayPrice}</span><span className="ml-2 text-xs text-slate-500">USD · once</span>{p.compareAt && <p className="mt-2 text-xs text-slate-500"><s>{p.compareAt}</s> · {p.savings}</p>}</div><ul className="mb-6 space-y-3">{productDetailsEN[id].includes.slice(0, 4).map(item => <li key={item} className="flex gap-2 text-sm text-slate-600"><Check className="h-4 w-4 shrink-0 text-[#0683C9]" />{item}</li>)}</ul><StoreCTA href={storePath('en', id)} productId={id} className={`${primaryButton} mt-auto`}>Explore {id === 'bundle' ? 'the Bundle' : id === 'ats' ? 'ATS Resume System' : 'the Tracker'}</StoreCTA></article>; })}</div>;
}
export function StoreFAQ() {
  const entries = [
    ['Is this a subscription?', 'No. You pay once and keep the downloaded resources for your own use.'],
    ['How do I receive my purchase?', 'After payment is confirmed, your secure access page opens and an access email is sent to the address entered at checkout. The Bundle includes separate Tracker and Resume downloads.'],
    ['Which language are the files in?', 'Purchases from the English store include the English resources. The French store includes French and English editions.'],
    ['Do I need special software?', 'The tracker is designed for Google Sheets, with setup instructions for its automations. Resume templates are editable; follow the included guide to choose the right format for your workflow.'],
    ['Will these tools guarantee an interview?', 'No tool can guarantee interviews or a job offer. These resources help you organise your search and communicate your experience more clearly.'],
    ['What if I need help with my download?', 'Email talentiques@gmail.com with your order reference. Our team can help restore access without asking you to pay again.'],
  ];
  return <section id="faq" className={section}><h2 className="text-3xl font-black">Before you get started</h2><div className="mt-8 divide-y divide-slate-200">{entries.map(([q, a]) => <details key={q} className="py-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{a}</p></details>)}</div></section>;
}
export default function EnglishStore({ productId }: { productId?: StoreProductId }) {
  const p = productId ? STORE_EN_PRODUCTS[productId] : null;
  const detail = productId ? productDetailsEN[productId] : null;
  return <><EnglishHeader /><main className="overflow-hidden bg-white text-[#0F172A]">
    <section className="bg-gradient-to-b from-sky-50 to-white"><div className={section}><div className="grid items-center gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0683C9]">TalentiQues career systems</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-tight sm:text-5xl">{detail?.headline ?? 'Turn your job search into a system you can trust.'}</h1><p className="mt-6 text-base leading-8 text-slate-600">{detail?.outcome ?? 'Organise your opportunities. Build a clearer resume. Follow through with confidence. Practical tools for today’s applications and your next career move.'}</p>{p && productId ? <StoreCTA href={`/en/tools/checkout?product=${productId}`} productId={productId} className={`${primaryButton} mt-7`}>Get {p.name} — {p.displayPrice}</StoreCTA> : <a href="#products" className={`${primaryButton} mt-7`}>Find your system <ArrowRight className="h-4 w-4" /></a>}<p className="mt-4 text-xs text-slate-500">Secure PayPal checkout · Prices in USD</p></div><EnglishProductVisual id={productId ?? 'bundle'} /></div><TrustStrip /></div></section>
    {detail && p ? <>
      <section className={section}><p className="text-xs font-bold uppercase tracking-widest text-[#0683C9]">From scattered effort to focused action</p><h2 className="mt-4 max-w-3xl text-3xl font-black">Your search deserves a repeatable process.</h2><p className="mt-5 max-w-3xl leading-8 text-slate-600">{detail.problem}</p><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{detail.benefits.map(item => <div key={item} className="rounded-2xl bg-slate-50 p-6"><CheckCircle2 className="mb-4 text-[#0683C9]" /><p className="font-semibold leading-6">{item}</p></div>)}</div></section>
      <section className="bg-slate-50"><div className={`${section} grid gap-10 lg:grid-cols-2`}><div><h2 className="text-3xl font-black">Everything included</h2><ul className="mt-6 space-y-4">{detail.includes.map(item => <li key={item} className="flex gap-3 text-sm leading-6"><Check className="h-5 w-5 shrink-0 text-[#0683C9]" />{item}</li>)}</ul></div><div><h2 className="text-3xl font-black">Put it to work</h2><ol className="mt-6 space-y-5">{detail.steps.map((step, index) => <li key={step} className="flex items-start gap-4"><span className="rounded-full bg-white px-3 py-1 font-bold text-[#0683C9]">{index + 1}</span><p className="text-sm leading-6 text-slate-600">{step}</p></li>)}</ol></div></div></section>
    </> : <section className={section}><h2 className="text-3xl font-black">A stronger application. A more organised search.</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{[['Find your focus', 'Keep your targets, contacts and next actions in one place.'], ['Make your experience count', 'Build a readable resume and tailor it to the role you want.'], ['Keep moving forward', 'Create a weekly routine for applications, follow-ups and interviews.']].map(([title, body]) => <article key={title} className="rounded-3xl bg-slate-50 p-7"><h3 className="text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></article>)}</div></section>}
    <section id="products" className="bg-sky-50/50"><div className={section}><h2 className="mb-8 text-3xl font-black">{p ? 'Choose the right scope for your search' : 'Two focused tools. One complete system.'}</h2><ProductCards /></div></section>
    <section className={section}><h2 className="text-3xl font-black">From checkout to your next action</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[[ShieldCheck, 'Pay securely', 'Choose your resource and complete a one-time PayPal payment.'], [CheckCircle2, 'Open your access page', 'Your resources unlock when payment is confirmed.'], [Download, 'Download and get started', 'Keep your files and find the access link in your email.']].map(([Icon, title, copy]) => { const I = Icon as typeof ShieldCheck; return <article key={String(title)} className="rounded-3xl border border-slate-200 p-6"><I className="text-[#0683C9]" /><h3 className="mt-5 font-bold">{String(title)}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{String(copy)}</p></article>; })}</div></section>
    <StoreFAQ /><section className="bg-[#0F172A] text-white"><div className={`${section} text-center`}><h2 className="text-3xl font-black sm:text-4xl">Build your foundation once. Keep moving forward.</h2><StoreCTA href={`/en/tools/checkout?product=${productId ?? 'bundle'}`} productId={productId ?? 'bundle'} className={`${primaryButton} mt-8`}>Get started — {(p ?? STORE_EN_PRODUCTS.bundle).displayPrice}</StoreCTA><p className="mt-5 text-sm text-slate-400">One-time payment · No subscription · English resources</p></div></section>
  </main><EnglishFooter /></>;
}
