import EnglishPage from '@/components/EnglishPage';
import { localizedMetadata } from '@/lib/i18n';
export const metadata = localizedMetadata('/en/blog', 'Career insights | TalentiQues', 'Practical guidance on clearer resumes, structured job searches, professional profiles and interview preparation.');
const guides = [
  { id: 'resume', title: 'A resume that helps readers find the evidence', paragraphs: ['Start with the role you are targeting. Choose the experience and skills that are genuinely relevant, and make those easy to find with conventional headings such as Experience, Education and Skills.', 'For each role, describe what you did, the context and the result. Use numbers when they are accurate and useful, not simply to decorate a bullet point. Avoid copying a job description into your resume or claiming skills you cannot demonstrate.', 'Keep the layout simple and test the exported file: can you select and copy the text in the correct order? Follow the employer’s requested file format. No template can guarantee that every applicant tracking system will parse a document perfectly.'] },
  { id: 'search', title: 'Build a job-search routine you can sustain', paragraphs: ['A useful tracker answers four questions: what is the role, why is it a fit, what has happened so far and what should happen next? Record the link and key details while the vacancy is still available.', 'Set aside separate time for finding opportunities, preparing applications and following up. A small number of well-targeted applications can be more useful than a high volume of generic submissions.', 'Review your progress each week. Look for patterns rather than treating every rejection as a verdict on your potential. Adjust your target roles, evidence or outreach when the information suggests a change.'] },
  { id: 'interviews', title: 'Prepare examples, not memorised speeches', paragraphs: ['Read the role description and identify the capabilities the interview is likely to explore. Choose examples from work, study or projects that show those capabilities in action.', 'Structure each example around the situation, your task, your own actions and the result. Be clear about what you personally contributed and what you learned. Practise out loud while leaving room for a natural conversation.', 'Prepare thoughtful questions about the team, priorities and how success is assessed. Confirm the format and practical details in advance, and make a brief note of what you learned afterwards.'] },
  { id: 'linkedin', title: 'Make your professional profile consistent', paragraphs: ['Your headline should help the right reader understand your direction. Use a clear role or area of expertise rather than a string of broad adjectives.', 'Use your summary to connect your experience, strengths and next step. Keep dates and job titles consistent with your resume. Include examples or projects you have permission to share, and remove confidential information.', 'When reaching out, explain why the conversation is relevant and make a specific, reasonable request. Personalised, respectful outreach is more useful than sending the same message to everyone.'] },
];
export default function Page() { return <EnglishPage title="Small improvements. A more deliberate career search." intro="Practical notes on the parts of a job search you can control.">{guides.map(guide => <article id={guide.id} key={guide.id} className="scroll-mt-8 rounded-3xl bg-slate-50 p-7 sm:p-10"><h2 className="text-2xl font-black">{guide.title}</h2>{guide.paragraphs.map(p => <p key={p} className="mt-5 leading-8 text-slate-600">{p}</p>)}</article>)}</EnglishPage>; }
