type Json = Record<string, unknown>;
function config() { const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY; if(!url||!key) throw new Error('Admin Supabase configuration missing'); return {url:url.replace(/\/$/,''),key}; }
function headers(extra:HeadersInit={}):HeadersInit { const {key}=config(); return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...extra}; }
async function parse(response:Response){const text=await response.text();const body=text?JSON.parse(text):null;if(!response.ok)throw new Error(body?.message||`Supabase ${response.status}`);return body;}
async function rpc(name:string,payload:Json){const {url}=config();return parse(await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:JSON.stringify(payload),cache:'no-store'}));}

export async function insertAdminLoginToken(payload:Json){const {url}=config();return parse(await fetch(`${url}/rest/v1/affiliate_admin_login_tokens`,{method:'POST',headers:headers(),body:JSON.stringify(payload),cache:'no-store'}));}
export async function hasRecentAdminToken(email:string,since:string){const {url}=config();const q=new URLSearchParams({email:`eq.${email}`,created_at:`gte.${since}`,select:'id',limit:'1'});const rows=await parse(await fetch(`${url}/rest/v1/affiliate_admin_login_tokens?${q}`,{headers:headers(),cache:'no-store'})) as Json[];return Boolean(rows[0]);}
export async function consumeAdminTokenHash(hash:string){const rows=await rpc('consume_affiliate_admin_login_token',{p_token_hash:hash}) as Json[];return rows?.[0]||null;}
export async function insertAdminSession(payload:Json){const {url}=config();return parse(await fetch(`${url}/rest/v1/affiliate_admin_sessions`,{method:'POST',headers:headers(),body:JSON.stringify(payload),cache:'no-store'}));}
export async function findAdminSession(hash:string){const {url}=config();const q=new URLSearchParams({session_hash:`eq.${hash}`,revoked_at:'is.null',expires_at:`gt.${new Date().toISOString()}`,limit:'1'});const rows=await parse(await fetch(`${url}/rest/v1/affiliate_admin_sessions?${q}`,{headers:headers(),cache:'no-store'})) as Json[];return rows?.[0]||null;}
export async function revokeAdminSession(hash:string){const {url}=config();const q=new URLSearchParams({session_hash:`eq.${hash}`,revoked_at:'is.null'});await parse(await fetch(`${url}/rest/v1/affiliate_admin_sessions?${q}`,{method:'PATCH',headers:headers(),body:JSON.stringify({revoked_at:new Date().toISOString()}),cache:'no-store'}));}
export async function adminOverview(){return rpc('affiliate_admin_overview',{});}
export async function payoutReady(){return rpc('affiliate_payout_ready',{}) as Promise<Json[]>;}
export async function releaseAllMature(){return rpc('release_all_mature_affiliate_commissions',{});}
export async function createPayoutBatch(currency:string,affiliateIds:string[],admin:string,notes?:string){return rpc('create_affiliate_payout_batch',{p_currency:currency,p_affiliate_ids:affiliateIds,p_admin:admin,p_notes:notes||null});}
export async function updatePayoutBatch(batchId:string,action:string,admin:string){return rpc('update_affiliate_payout_batch',{p_batch_id:batchId,p_action:action,p_admin:admin});}
export async function completePayoutItem(itemId:string,result:string,admin:string,reference?:string,reason?:string){return rpc('complete_affiliate_payout_item',{p_item_id:itemId,p_result:result,p_admin:admin,p_external_reference:reference||null,p_reason:reason||null});}
export async function createPaidAdjustment(orderId:string,reason:string){return rpc('create_paid_affiliate_adjustment',{p_order_id:orderId,p_reason:reason});}

export async function paginated(table:string,params:Record<string,string>,page=1,pageSize=25){const {url}=config();const safeSize=[25,50,100].includes(pageSize)?pageSize:25;const start=(Math.max(page,1)-1)*safeSize;const q=new URLSearchParams(params);const response=await fetch(`${url}/rest/v1/${table}?${q}`,{headers:headers({Prefer:'count=exact',Range:`${start}-${start+safeSize-1}`}),cache:'no-store'});const rows=await parse(response) as Json[];const range=response.headers.get('content-range');const total=Number(range?.split('/')[1]||rows.length);return {rows,total,page:Math.max(page,1),pageSize:safeSize};}
export function listAffiliates(options:{status?:string;search?:string;page?:number;pageSize?:number;oldest?:boolean}){const params:Record<string,string>={select:'id,code,full_name,email,country,status,commission_rate,payout_method,payout_email,primary_channel,profile_url,audience_size,content_focus,motivation,application_language,rejection_reason,created_at,approved_at',order:options.oldest?'created_at.asc':'created_at.desc'};if(options.status)params.status=`eq.${options.status}`;const search=options.search?.replace(/[^\p{L}\p{N}@._ -]/gu,'').slice(0,100);if(search)params.or=`(full_name.ilike.*${search}*,email.ilike.*${search}*,code.ilike.*${search}*)`;return paginated('affiliates',params,options.page,options.pageSize);}
export async function getAdminAffiliate(id:string){const {url}=config();const q=new URLSearchParams({id:`eq.${id}`,select:'*',limit:'1'});const rows=await parse(await fetch(`${url}/rest/v1/affiliates?${q}`,{headers:headers(),cache:'no-store'})) as Json[];return rows?.[0]||null;}
export function listCommissions(options:{status?:string;currency?:string;page?:number;pageSize?:number}){const params:Record<string,string>={select:'id,affiliate_id,order_id,product_id,market,order_amount,commission_rate,commission_amount,currency,status,reason,created_at,available_at,paid_at,payout_batch_item_id,affiliate:affiliates(full_name,email,code)',order:'created_at.desc'};if(options.status)params.status=`eq.${options.status}`;if(options.currency)params.currency=`eq.${options.currency}`;return paginated('affiliate_commissions',params,options.page,options.pageSize);}
export function listBatches(page=1,pageSize=25){return paginated('affiliate_payout_batches',{select:'*',order:'created_at.desc'},page,pageSize);}
export async function getBatch(id:string){const {url}=config();const batchQ=new URLSearchParams({id:`eq.${id}`,limit:'1'});const itemQ=new URLSearchParams({batch_id:`eq.${id}`,select:'*,affiliate:affiliates(full_name,email,code,country,payout_method,payout_email)',order:'created_at.asc'});const [batches,items]=await Promise.all([parse(await fetch(`${url}/rest/v1/affiliate_payout_batches?${batchQ}`,{headers:headers(),cache:'no-store'})) as Promise<Json[]>,parse(await fetch(`${url}/rest/v1/affiliate_payout_batch_items?${itemQ}`,{headers:headers(),cache:'no-store'})) as Promise<Json[]>]);return {batch:batches[0]||null,items};}
export async function getPayoutItem(id:string){const {url}=config();const q=new URLSearchParams({id:`eq.${id}`,select:'*,affiliate:affiliates(full_name,email,code,application_language)',limit:'1'});const rows=await parse(await fetch(`${url}/rest/v1/affiliate_payout_batch_items?${q}`,{headers:headers(),cache:'no-store'})) as Json[];return rows[0]||null;}
export async function addAdminNote(affiliateId:string,note:string,admin:string){const {url}=config();return parse(await fetch(`${url}/rest/v1/affiliate_admin_notes`,{method:'POST',headers:headers(),body:JSON.stringify({affiliate_id:affiliateId,note,created_by:admin}),cache:'no-store'}));}
export function listAdminNotes(affiliateId:string){return paginated('affiliate_admin_notes',{affiliate_id:`eq.${affiliateId}`,select:'id,note,created_by,created_at',order:'created_at.desc'},1,100);}
export function listAdjustments(page=1,pageSize=100){return paginated('affiliate_adjustments',{select:'*,affiliate:affiliates(full_name,email,code)',order:'created_at.desc'},page,pageSize);}
export function listAudit(page=1,pageSize=100){return paginated('affiliate_admin_audit_log',{select:'*',order:'created_at.desc'},page,pageSize);}
export async function insertAdminAudit(payload:Json){const {url}=config();return parse(await fetch(`${url}/rest/v1/affiliate_admin_audit_log`,{method:'POST',headers:headers(),body:JSON.stringify(payload),cache:'no-store'}));}
