'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { BarChart3, Check, CircleDollarSign, Copy, Gift, Link2, LogOut, Menu, MousePointerClick, UserRound, WalletCards, X } from 'lucide-react';
import type { AffiliateDashboardData, DashboardPeriod } from '@/lib/affiliate/dashboard';

const productNames: Record<string, { fr: string; en: string }> = {
  tracker: { fr: 'Opportunity Tracker', en: 'Application Tracker' },
  ats: { fr: 'CV ATS & LinkedIn', en: 'ATS Resume & LinkedIn' },
  bundle: { fr: 'Career Search Bundle', en: 'Career Search Bundle' },
};

function money(value: number, currency: unknown, locale: 'fr' | 'en') {
  return new Intl.NumberFormat(locale === 'fr' ? 'fr-FR' : 'en-US', { style: 'currency', currency: currency === 'USD' ? 'USD' : 'EUR' }).format(value);
}

function Amounts({ values, locale }: { values: Record<string, number>; locale: 'fr' | 'en' }) {
  const entries = Object.entries(values);
  if (!entries.length) return <span>—</span>;
  return <span className="flex flex-col">{entries.map(([currency, value]) => <span key={currency}>{money(value, currency, locale)}</span>)}</span>;
}

export default function AffiliateDashboard({ initialData, locale }: { initialData: AffiliateDashboardData; locale: 'fr' | 'en' }) {
  const [data, setData] = useState(initialData); const [menu, setMenu] = useState(false); const [copied, setCopied] = useState('');
  const [market, setMarket] = useState<'fr' | 'en'>('fr'); const [tracking, setTracking] = useState({ utm_source: '', utm_medium: '', utm_campaign: '', utm_content: '' });
  const fr = locale === 'fr'; const firstName = String(data.affiliate.fullName || '').split(/\s+/)[0];
  const nav = [['overview', fr ? 'Vue d’ensemble' : 'Overview', BarChart3], ['links', fr ? 'Liens' : 'Links', Link2], ['commissions', fr ? 'Commissions' : 'Commissions', CircleDollarSign], ['payouts', fr ? 'Paiements' : 'Payouts', WalletCards], ['kit', fr ? 'Kit de promotion' : 'Promotion Kit', Gift], ['account', fr ? 'Compte' : 'Account', UserRound]] as const;
  const generatedLink = useMemo(() => { const url = new URL(market === 'fr' ? data.links.fr : data.links.en); for (const [key, value] of Object.entries(tracking)) if (value.trim()) url.searchParams.set(key, value.trim().slice(0, 100)); return url.toString(); }, [data.links, market, tracking]);
  async function copy(value: string, id: string) { await navigator.clipboard.writeText(value); setCopied(id); window.setTimeout(() => setCopied(''), 1800); }
  async function period(value: DashboardPeriod) { const response = await fetch(`/api/affiliate/dashboard?period=${value}`); if (response.ok) setData(await response.json()); }
  return <div className="min-h-screen bg-slate-50 text-slate-950">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur lg:hidden"><div className="flex h-16 items-center justify-between px-5"><span className="font-heading text-xl font-bold text-[#0683C9]">TalentiQues</span><button onClick={() => setMenu(!menu)} aria-label="Menu" className="rounded-lg p-2">{menu ? <X /> : <Menu />}</button></div>{menu && <nav className="border-t border-slate-100 p-3">{nav.map(([id, label]) => <a onClick={() => setMenu(false)} key={id} href={`#${id}`} className="block rounded-lg px-3 py-3 font-semibold text-slate-700">{label}</a>)}</nav>}</header>
    <aside className="fixed inset-y-0 left-0 hidden w-64 bg-[#071b2b] p-6 text-white lg:flex lg:flex-col"><Link href={fr ? '/affiliation' : '/en/affiliate'} className="font-heading text-2xl font-bold">TalentiQues</Link><p className="mt-2 text-xs font-bold tracking-[.16em] text-sky-300">{fr ? 'ESPACE AFFILIÉ' : 'AFFILIATE PORTAL'}</p><nav className="mt-10 space-y-1">{nav.map(([id, label, Icon]) => <a key={id} href={`#${id}`} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-300 hover:bg-white/10 hover:text-white"><Icon size={18} />{label}</a>)}</nav><form className="mt-auto" action={`/api/affiliate/auth/logout?lang=${locale}`} method="post"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-300 hover:bg-white/10"><LogOut size={18} />{fr ? 'Se déconnecter' : 'Log out'}</button></form></aside>
    <main className="px-4 py-8 sm:px-6 lg:ml-64 lg:px-10 lg:py-10"><div className="mx-auto max-w-7xl">
      <section id="overview"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />{fr ? 'Affilié actif' : 'Active Affiliate'}</div><h1 className="mt-4 font-heading text-3xl font-bold sm:text-5xl">{fr ? `Bonjour, ${firstName}` : `Welcome back, ${firstName}`}</h1><p className="mt-3 text-slate-600">{fr ? 'Voici les performances de votre programme d’affiliation Talentiques.' : 'Here’s how your Talentiques referrals are performing.'}</p></div><div className="flex rounded-xl border border-slate-200 bg-white p-1">{(['today', '7d', '30d', 'all'] as DashboardPeriod[]).map((value) => <button onClick={() => void period(value)} key={value} className={`rounded-lg px-3 py-2 text-xs font-bold ${data.period === value ? 'bg-[#0683C9] text-white' : 'text-slate-500'}`}>{value === 'today' ? (fr ? 'Aujourd’hui' : 'Today') : value === 'all' ? (fr ? 'Tout' : 'All') : value}</button>)}</div></div>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Kpi label={fr ? 'Clics' : 'Clicks'} value={String(data.metrics.clicks)} icon={<MousePointerClick />} /><Kpi label={fr ? 'Ventes' : 'Sales'} value={String(data.metrics.sales)} icon={<CircleDollarSign />} /><Kpi label={fr ? 'Taux de conversion' : 'Conversion rate'} value={`${data.metrics.conversionRate}%`} icon={<BarChart3 />} /><Kpi label={fr ? 'Revenu généré' : 'Revenue generated'} value={<Amounts values={data.metrics.revenue} locale={locale} />} /><Kpi label={fr ? 'Commission en attente' : 'Pending commission'} value={<Amounts values={data.metrics.balances.pending} locale={locale} />} /><Kpi label={fr ? 'Commission disponible' : 'Available commission'} value={<Amounts values={data.metrics.balances.available} locale={locale} />} /><Kpi label={fr ? 'Commission payée' : 'Paid commission'} value={<Amounts values={data.metrics.balances.paid} locale={locale} />} /></div>
      <PerformanceChart data={data.chart} locale={locale} /></section>

      <section id="links" className="mt-10 rounded-3xl border border-slate-200 bg-white p-5 sm:p-8"><SectionTitle title={fr ? 'Vos liens affiliés' : 'Your referral links'} subtitle={`${fr ? 'Code affilié' : 'Affiliate code'}: ${data.affiliate.code} · 50% · ${fr ? '30 jours' : '30 days'}`} /><div className="mt-6 space-y-3"><CopyRow label="FR" value={data.links.fr} copied={copied} onCopy={copy} /><CopyRow label="EN" value={data.links.en} copied={copied} onCopy={copy} /></div><div className="mt-8 border-t border-slate-100 pt-7"><h3 className="font-heading text-xl font-bold">{fr ? 'Générateur de lien' : 'Link builder'}</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><select className="input" value={market} onChange={(event) => setMarket(event.target.value as 'fr' | 'en')}><option value="fr">FR</option><option value="en">EN</option></select>{Object.keys(tracking).map((key) => <input key={key} className="input" placeholder={key} value={tracking[key as keyof typeof tracking]} onChange={(event) => setTracking({ ...tracking, [key]: event.target.value })} />)}</div><div className="mt-4"><CopyRow label="URL" value={generatedLink} copied={copied} onCopy={copy} /></div></div></section>

      <section id="commissions" className="mt-10"><SectionTitle title={fr ? 'Ventes récentes' : 'Recent sales'} subtitle={fr ? 'Aucune donnée client personnelle n’est affichée.' : 'No customer personal data is displayed.'} /><DataTable rows={data.recentSales} locale={locale} empty={fr ? 'Partagez votre lien pour commencer à mesurer vos performances.' : 'Share your referral link to start tracking your performance.'} /><div className="mt-10"><SectionTitle title={fr ? 'Historique des commissions' : 'Commission history'} subtitle={fr ? 'Les commissions deviennent disponibles 30 jours après une vente éligible, sous réserve d’absence de remboursement ou de litige.' : 'Commissions become available 30 days after an eligible sale, provided the transaction has not been refunded or disputed.'} /><DataTable rows={data.commissionHistory} locale={locale} empty={fr ? 'Aucune commission pour le moment.' : 'No commissions yet.'} /></div></section>

      <section id="payouts" className="mt-10 grid gap-5 lg:grid-cols-[.35fr_.65fr]"><div className="rounded-3xl bg-[#071b2b] p-7 text-white"><p className="text-sm font-bold text-sky-300">{fr ? 'PAIEMENTS MENSUELS' : 'MONTHLY PAYOUTS'}</p><h2 className="mt-4 font-heading text-3xl font-bold">{fr ? 'Seuil : 20 € ou 20 $' : 'Threshold: €20 or $20'}</h2><p className="mt-4 leading-7 text-slate-300">{fr ? 'Le seuil est calculé séparément pour chaque solde de devise.' : 'The threshold is calculated separately for each currency balance.'}</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-heading text-2xl font-bold">{fr ? 'Historique des paiements' : 'Payout history'}</h2>{data.payouts.length ? <div className="mt-5 space-y-3">{data.payouts.map((item, index) => <div key={index} className="flex items-center justify-between border-b border-slate-100 py-3"><span>{new Date(String(item.date)).toLocaleDateString(locale)}</span><strong>{money(item.amount, item.currency, locale)}</strong><Status value={String(item.status)} locale={locale} /></div>)}</div> : <p className="mt-6 text-slate-500">{fr ? 'Aucun paiement enregistré pour le moment.' : 'No payouts yet.'}</p>}</div></section>

      <section id="kit" className="mt-10 rounded-3xl border border-slate-200 bg-white p-5 sm:p-8"><SectionTitle title={fr ? 'Kit de promotion' : 'Promotion Kit'} subtitle={fr ? 'Des liens et textes prêts à adapter à votre audience.' : 'Links and copy you can adapt for your audience.'} /><div className="mt-7 grid gap-5 lg:grid-cols-3">{(['tracker', 'ats', 'bundle'] as const).map((product) => <article key={product} className="rounded-2xl bg-slate-50 p-5"><h3 className="font-heading text-lg font-bold">{productNames[product][locale]}</h3><div className="mt-4 space-y-2"><CopyRow label="FR" value={data.links.products.fr[product]} copied={copied} onCopy={copy} /><CopyRow label="EN" value={data.links.products.en[product]} copied={copied} onCopy={copy} /></div></article>)}</div><div className="mt-7 grid gap-5 lg:grid-cols-2"><CopyBlock title={fr ? 'Texte social — organisation' : 'Social copy — organization'} text={fr ? `Vous gérez encore votre recherche d’emploi entre des onglets, notes et relances oubliées ?\n\nTalentiques réunit candidatures, CV ATS, LinkedIn et ressources carrière dans un système structuré.\n\nDécouvrez-le ici :\n${data.links.fr}` : `Still managing your career search across tabs, notes and forgotten follow-ups?\n\nTalentiques brings your applications, ATS resume, LinkedIn and career-search resources into one structured system.\n\nExplore it here:\n${data.links.en}`} onCopy={copy} copied={copied} /><CopyBlock title={fr ? 'Texte social — outils carrière' : 'Social copy — career tools'} text={fr ? `Une recherche d’emploi plus structurée commence avec les bons outils.\n\nDécouvrez les ressources Talentiques pour suivre vos candidatures, renforcer votre CV ATS et optimiser votre présence LinkedIn.\n\n${data.links.fr}` : `A more structured career search starts with the right tools.\n\nExplore Talentiques resources to track applications, strengthen your ATS resume and improve your LinkedIn presence.\n\n${data.links.en}`} onCopy={copy} copied={copied} /><div className="rounded-2xl bg-sky-50 p-6 lg:col-span-2"><h3 className="font-heading text-xl font-bold">{fr ? 'Rappel de transparence' : 'Disclosure reminder'}</h3><p className="mt-3 leading-7 text-slate-600">{fr ? 'Lorsque cela est requis, indiquez clairement à votre audience que votre lien est un lien affilié.' : 'Where required, clearly disclose to your audience that you may earn a commission through your affiliate link.'}</p><p className="mt-5 text-sm font-bold text-[#0683C9]">{fr ? 'CTA : Découvrir Talentiques · Construire une recherche plus efficace · Découvrir les outils carrière' : 'CTA: Explore Talentiques · Build a smarter career search · Discover the career tools'}</p></div></div></section>

      <section id="account" className="my-10 rounded-3xl border border-slate-200 bg-white p-5 sm:p-8"><SectionTitle title={fr ? 'Compte affilié' : 'Affiliate account'} subtitle={fr ? 'Informations en lecture seule.' : 'Read-only account information.'} /><dl className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[[fr ? 'Nom' : 'Name', data.affiliate.fullName], ['Email', data.affiliate.email], [fr ? 'Pays' : 'Country', data.affiliate.country], [fr ? 'Code affilié' : 'Affiliate code', data.affiliate.code], [fr ? 'Canal principal' : 'Primary channel', data.affiliate.primaryChannel], ['Profile URL', data.affiliate.profileUrl], [fr ? 'Commission' : 'Commission rate', `${data.affiliate.commissionRate * 100}%`], [fr ? 'Statut' : 'Status', data.affiliate.status], [fr ? 'Date d’approbation' : 'Approved date', data.affiliate.approvedAt ? new Date(String(data.affiliate.approvedAt)).toLocaleDateString(locale) : '—']].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">{String(label)}</dt><dd className="mt-2 break-words font-semibold text-slate-800">{String(value || '—')}</dd></div>)}</dl></section>
    </div></main>
  </div>;
}

function Kpi({ label, value, icon }: { label: string; value: React.ReactNode; icon?: React.ReactNode }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between text-slate-400"><p className="text-sm font-semibold">{label}</p>{icon}</div><div className="mt-4 font-heading text-3xl font-bold text-slate-950">{value}</div></article>; }
function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div><h2 className="font-heading text-2xl font-bold sm:text-3xl">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p></div>; }
function CopyRow({ label, value, copied, onCopy }: { label: string; value: string; copied: string; onCopy: (value: string, id: string) => void }) { const id = `${label}-${value}`; return <div className="flex min-w-0 items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><span className="shrink-0 text-xs font-bold text-[#0683C9]">{label}</span><code className="min-w-0 flex-1 truncate text-xs text-slate-600">{value}</code><button aria-label={`Copy ${label}`} onClick={() => void onCopy(value, id)} className="shrink-0 rounded-lg bg-slate-100 p-2 text-slate-600">{copied === id ? <Check size={16} /> : <Copy size={16} />}</button></div>; }
function CopyBlock({ title, text, onCopy, copied }: { title: string; text: string; onCopy: (value: string, id: string) => void; copied: string }) { return <div className="rounded-2xl bg-slate-950 p-6 text-white"><div className="flex justify-between"><h3 className="font-heading text-xl font-bold">{title}</h3><button aria-label={`Copy ${title}`} onClick={() => void onCopy(text, title)}>{copied === title ? <Check /> : <Copy />}</button></div><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-300">{text}</p></div>; }
function Status({ value, locale }: { value: string; locale: 'fr' | 'en' }) { const labels: Record<string, string> = locale === 'fr' ? { pending: 'En attente', available: 'Disponible', paid: 'Payée', cancelled: 'Annulée', processing: 'Traitement', failed: 'Échec' } : { pending: 'Pending', available: 'Available', paid: 'Paid', cancelled: 'Cancelled', processing: 'Processing', failed: 'Failed' }; return <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{labels[value] || value}</span>; }
function DataTable({ rows, locale, empty }: { rows: AffiliateDashboardData['commissionHistory']; locale: 'fr' | 'en'; empty: string }) { const fr = locale === 'fr'; if (!rows.length) return <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500">{empty}</div>; return <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[720px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{[fr ? 'Date' : 'Date', fr ? 'Produit' : 'Product', fr ? 'Marché' : 'Market', fr ? 'Vente' : 'Sale', fr ? 'Commission' : 'Commission', fr ? 'Statut' : 'Status'].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{rows.map((item, index) => <tr key={index} className="border-t border-slate-100"><td className="px-4 py-4">{new Date(String(item.date)).toLocaleDateString(locale, { day: '2-digit', month: 'short' })}</td><td className="px-4 py-4 font-semibold">{productNames[String(item.productId)]?.[locale] || String(item.productId)}</td><td className="px-4 py-4 uppercase">{String(item.market)}</td><td className="px-4 py-4">{money(item.orderAmount, item.currency, locale)}</td><td className="px-4 py-4 font-bold text-[#0683C9]">{money(item.commissionAmount, item.currency, locale)}</td><td className="px-4 py-4"><Status value={String(item.status)} locale={locale} /></td></tr>)}</tbody></table></div>; }
function PerformanceChart({ data, locale }: { data: AffiliateDashboardData['chart']; locale: 'fr' | 'en' }) { const max = Math.max(1, ...data.flatMap((item) => [item.clicks, item.sales])); return <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="font-heading text-xl font-bold">{locale === 'fr' ? 'Performance sur 30 jours' : '30-day performance'}</h2><div className="flex gap-4 text-xs font-bold"><span className="text-[#0683C9]">● {locale === 'fr' ? 'Clics' : 'Clicks'}</span><span className="text-emerald-500">● {locale === 'fr' ? 'Ventes' : 'Sales'}</span></div></div><div className="mt-7 flex h-44 items-end gap-1" aria-label="30-day clicks and sales chart">{data.map((item) => <div key={item.date} className="flex h-full min-w-0 flex-1 items-end gap-px" title={`${item.date}: ${item.clicks} clicks, ${item.sales} sales`}><span className="w-1/2 rounded-t bg-[#0683C9]" style={{ height: `${Math.max(2, item.clicks / max * 100)}%` }} /><span className="w-1/2 rounded-t bg-emerald-400" style={{ height: `${Math.max(2, item.sales / max * 100)}%` }} /></div>)}</div></section>; }
