import Link from 'next/link';
import { ArrowRight, BadgeCheck, CalendarDays, Check, Megaphone, Percent, Sparkles } from 'lucide-react';
import AffiliateApplicationForm from './AffiliateApplicationForm';
import { getCurrentAffiliate } from '@/lib/affiliate/auth';

const data = {
  fr: {
    eyebrow: 'PROGRAMME D’AFFILIATION TALENTIQUES', headline: <>Recommandez Talentiques.<br /><span className="text-sky-300">Gagnez 50 %</span> sur chaque vente.</>,
    copy: 'Vous créez du contenu autour de l’emploi, des études, de la carrière, du CV, de LinkedIn ou de la mobilité professionnelle ? Recommandez les outils Talentiques à votre audience et recevez 50 % de commission sur chaque vente attribuée à votre lien.',
    trust: ['Inscription gratuite', 'Lien personnel', 'Attribution 30 jours', 'Paiements mensuels'], cta: 'Devenir affilié', howCta: 'Voir comment ça fonctionne', localeLink: '/en/affiliate', localeLabel: 'English',
    valuesTitle: 'Un programme simple, pensé pour votre audience', values: [['50 % de commission', 'Une commission sur chaque vente éligible générée par votre lien.'], ['30 jours d’attribution', 'Votre recommandation reste attribuée pendant 30 jours après un clic valide.'], ['Produits digitaux accessibles', 'Des outils carrière à partir de 7,90 €, faciles à présenter à une audience.'], ['Ressources marketing', 'Talentiques pourra fournir visuels, vidéos, textes et idées de contenu.']],
    examplesTitle: 'Ce que vous pouvez gagner par vente', products: [['Tracker', '7,90 €', '3,95 €'], ['CV ATS & LinkedIn', '9,90 €', '4,95 €'], ['Bundle', '14,90 €', '7,45 €']], commission: 'Commission', disclaimer: 'Exemples basés sur une commission de 50 %. Les remboursements et litiges ne donnent pas droit à commission.',
    howTitle: 'Comment ça fonctionne', steps: [['01', 'Candidatez', 'Présentez rapidement votre profil, votre audience et vos canaux.'], ['02', 'Validation Talentiques', 'Nous vérifions votre candidature avant activation.'], ['03', 'Partagez votre lien', 'Après validation, utilisez votre lien personnel dans vos contenus.'], ['04', 'Gagnez 50 %', 'Chaque vente éligible attribuée à votre lien génère une commission.']],
    whoTitle: 'Qui peut candidater ?', whoIntro: 'La pertinence de votre contenu compte plus que la taille de votre audience.', who: ['Créateurs TikTok / Instagram / YouTube', 'Créateurs LinkedIn', 'Pages emploi / stage / alternance', 'Coachs carrière', 'Associations étudiantes', 'Pages mobilité internationale', 'Écoles / communautés étudiantes', 'Micro-influenceurs carrière', 'Blogs et newsletters carrière'],
    formEyebrow: 'REJOINDRE LE PROGRAMME', formTitle: 'Prêt à recommander des outils carrière utiles ?', terms: '/affiliation/conditions', termsLabel: 'Conditions du programme', sticky: 'Devenir affilié — 50 %',
  },
  en: {
    eyebrow: 'TALENTIQUES AFFILIATE PROGRAM', headline: <>Recommend Talentiques.<br /><span className="text-sky-300">Earn 50%</span> on every successful sale.</>,
    copy: 'Create content around careers, jobs, internships, resumes, LinkedIn, education or international opportunities? Recommend Talentiques career tools to your audience and earn a 50% commission on every eligible sale attributed to your link.',
    trust: ['Free to join', 'Personal referral link', '30-day attribution', 'Monthly payouts'], cta: 'Apply to join', howCta: 'See how it works', localeLink: '/affiliation', localeLabel: 'Français',
    valuesTitle: 'A straightforward program built for your audience', values: [['50% commission', 'Earn commission on every eligible sale generated through your referral link.'], ['30-day attribution', 'A valid referral remains attributed for 30 days.'], ['Accessible digital products', 'Career tools starting at $7.90, designed for a broad career-focused audience.'], ['Marketing resources', 'Access ready-to-use visuals, videos, messaging and content ideas.']],
    examplesTitle: 'What you can earn per sale', products: [['Application Tracker', '$7.90', '$3.95'], ['ATS Resume & LinkedIn', '$9.90', '$4.95'], ['Career Search Bundle', '$14.90', '$7.45']], commission: 'Commission', disclaimer: 'Examples based on a 50% commission rate. Refunded or disputed orders are not commissionable.',
    howTitle: 'How it works', steps: [['01', 'Apply', 'Tell us briefly about your audience and content channels.'], ['02', 'Talentiques review', 'Your application is reviewed before activation.'], ['03', 'Share your link', 'Once approved, promote Talentiques using your personal referral link.'], ['04', 'Earn 50%', 'Every eligible sale attributed to your link generates commission.']],
    whoTitle: 'Who can apply?', whoIntro: 'Relevant content matters more than audience size.', who: ['TikTok / Instagram / YouTube creators', 'LinkedIn creators', 'Job and internship pages', 'Career coaches', 'Student associations', 'International mobility creators', 'Student communities', 'Career micro-influencers', 'Career blogs and newsletters'],
    formEyebrow: 'JOIN THE PROGRAM', formTitle: 'Ready to recommend useful career tools?', terms: '/en/affiliate/terms', termsLabel: 'Program terms', sticky: 'Apply — 50% commission',
  },
};

const valueIcons = [Percent, CalendarDays, Sparkles, Megaphone];

export default async function AffiliateProgramPage({ locale }: { locale: 'fr' | 'en' }) {
  const t = data[locale];
  const authenticated = Boolean(await getCurrentAffiliate());
  const portalHref = locale === 'fr'
    ? authenticated ? '/affiliation/espace' : '/affiliation/connexion'
    : authenticated ? '/en/affiliate/dashboard' : '/en/affiliate/login';
  const portalLabel = authenticated
    ? locale === 'fr' ? 'Accéder à mon espace' : 'Open my dashboard'
    : locale === 'fr' ? 'Déjà affilié ? Se connecter' : 'Already an affiliate? Sign in';
  return <main className="min-h-screen bg-white text-slate-950">
    <header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href={locale === 'fr' ? '/' : '/en/tools'} className="font-heading text-2xl font-bold text-white">TalentiQues</Link><div className="flex items-center gap-4"><Link href={t.localeLink} className="text-sm font-semibold text-slate-300 hover:text-white">{t.localeLabel}</Link><Link href={portalHref} className="hidden rounded-full bg-white px-5 py-2.5 text-sm font-bold text-slate-950 sm:inline-flex">{portalLabel}</Link></div></div></header>
    <section className="relative overflow-hidden bg-[#071b2b] px-5 pb-24 pt-36 text-white lg:pb-32 lg:pt-44"><div className="absolute inset-0 opacity-70 [background:radial-gradient(circle_at_78%_20%,rgba(6,131,201,.45),transparent_28%),radial-gradient(circle_at_12%_90%,rgba(14,165,233,.18),transparent_30%)]" /><div className="relative mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="inline-flex rounded-full border border-sky-300/20 bg-sky-400/10 px-4 py-2 text-xs font-bold tracking-[.18em] text-sky-200">{t.eyebrow}</div><h1 className="mt-7 max-w-4xl font-heading text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">{t.headline}</h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">{t.copy}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#apply" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-[#0683C9] px-7 font-bold text-white hover:bg-sky-500">{t.cta}<ArrowRight size={18} /></a><a href="#how" className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/20 px-7 font-bold text-white hover:bg-white/5">{t.howCta}</a></div><div className="mt-9 flex flex-wrap gap-x-5 gap-y-3">{t.trust.map((item) => <span key={item} className="flex items-center gap-2 text-sm text-slate-300"><Check size={16} className="text-sky-300" />{item}</span>)}</div></div><div className="relative mx-auto w-full max-w-md"><div className="rounded-[2rem] border border-white/10 bg-white/[.07] p-7 shadow-2xl backdrop-blur"><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-300">50% commission</p><div className="my-8 flex items-end gap-3"><span className="font-heading text-8xl font-bold">50</span><span className="mb-3 text-4xl font-bold text-sky-300">%</span></div><div className="space-y-4 border-t border-white/10 pt-6">{t.trust.slice(1).map((item) => <div key={item} className="flex items-center gap-3"><BadgeCheck className="text-sky-300" size={20} /><span className="text-slate-200">{item}</span></div>)}</div></div></div></div></section>
    <section className="px-5 py-20 lg:py-28"><div className="mx-auto max-w-7xl"><h2 className="max-w-3xl font-heading text-3xl font-bold tracking-tight sm:text-5xl">{t.valuesTitle}</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{t.values.map(([title, text], index) => { const Icon = valueIcons[index]; return <article key={title} className="rounded-3xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:shadow-xl"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-50 text-[#0683C9]"><Icon /></span><h3 className="mt-6 font-heading text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>; })}</div></div></section>
    <section className="bg-slate-50 px-5 py-20 lg:py-28"><div className="mx-auto max-w-7xl"><h2 className="font-heading text-3xl font-bold sm:text-5xl">{t.examplesTitle}</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{t.products.map(([name, price, amount]) => <article key={name} className="rounded-3xl border border-slate-200 bg-white p-7"><p className="font-heading text-xl font-bold">{name}</p><p className="mt-2 text-slate-500">{price}</p><div className="mt-8 border-t border-slate-100 pt-6"><p className="text-sm font-semibold text-slate-500">{t.commission}</p><p className="mt-1 font-heading text-4xl font-bold text-[#0683C9]">{amount}</p></div></article>)}</div><p className="mt-6 text-sm leading-6 text-slate-500">{t.disclaimer}</p></div></section>
    <section id="how" className="bg-[#071b2b] px-5 py-20 text-white lg:py-28"><div className="mx-auto max-w-7xl"><h2 className="font-heading text-3xl font-bold sm:text-5xl">{t.howTitle}</h2><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{t.steps.map(([number, title, text]) => <article className="bg-[#0a2235] p-7" key={number}><p className="font-heading text-4xl font-bold text-sky-300">{number}</p><h3 className="mt-8 font-heading text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p></article>)}</div></div></section>
    <section className="px-5 py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><h2 className="font-heading text-3xl font-bold sm:text-5xl">{t.whoTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{t.whoIntro}</p></div><div className="grid gap-3 sm:grid-cols-2">{t.who.map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4 font-semibold text-slate-700"><Check className="shrink-0 text-[#0683C9]" size={18} />{item}</div>)}</div></div></section>
    <section id="apply" className="bg-slate-50 px-5 py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.72fr_1.28fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="text-sm font-bold tracking-[.16em] text-[#0683C9]">{t.formEyebrow}</p><h2 className="mt-4 font-heading text-3xl font-bold sm:text-5xl">{t.formTitle}</h2><Link href={t.terms} className="mt-7 inline-flex items-center gap-2 font-bold text-[#0683C9]">{t.termsLabel}<ArrowRight size={17} /></Link></div><AffiliateApplicationForm locale={locale} /></div></section>
    <footer className="bg-[#071b2b] px-5 py-10 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} TalentiQues</span><div className="flex gap-5"><Link href={t.terms}>{t.termsLabel}</Link><Link href="/politique-de-confidentialite">Privacy</Link></div></div></footer>
    <a href="#apply" className="fixed inset-x-4 bottom-4 z-30 flex min-h-14 items-center justify-center rounded-full bg-[#0683C9] px-5 font-bold text-white shadow-2xl sm:hidden">{t.sticky}</a>
  </main>;
}
