import Link from 'next/link';
import EnglishPage from '@/components/EnglishPage';
import EnglishLeadForm from '@/components/EnglishLeadForm';
import { ProductCards, primaryButton } from '@/components/store/EnglishStore';
import { localizedMetadata } from '@/lib/i18n';
export const metadata = localizedMetadata('/en', 'Career tools and support | TalentiQues', 'Build a clearer resume, organise your job search and move forward with practical career systems and personalised support from TalentiQues.');
export default function Page() {
  return <EnglishPage title="A clearer direction. A stronger application. A search you can manage." intro="Your next career move needs more than another document. TalentiQues brings practical tools, useful guidance and personalised support together so you can take the next step with confidence.">
    <div className="flex flex-wrap gap-4"><Link href="/en/tools" className={primaryButton}>Explore career tools</Link><Link href="/en/coaching" className="rounded-full border border-slate-300 px-6 py-3.5 text-sm font-bold">Find personalised support</Link></div>
    <section><h2 className="text-3xl font-black">Career progress, made practical.</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{[['Clarify your direction', 'Turn broad ambitions into a focused target: the roles, markets and skills that make sense for your next move.'], ['Make your experience visible', 'Build a resume and LinkedIn profile that communicate your strengths clearly, without inflated claims or generic language.'], ['Create a sustainable routine', 'Track opportunities, plan your follow-ups and prepare for interviews with a repeatable process.']].map(([title, copy]) => <article key={title} className="rounded-3xl bg-slate-50 p-7"><h3 className="text-xl font-bold">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{copy}</p></article>)}</div></section>
    <section><h2 className="mb-7 text-3xl font-black">Tools you own. Systems you can reuse.</h2><ProductCards /></section>
    <section className="rounded-3xl bg-[#0F172A] p-8 text-white"><h2 className="text-3xl font-black">Independent when you can be. Supported when you need it.</h2><p className="mt-5 max-w-3xl leading-8 text-slate-300">Start with self-serve resources or discuss a tailored coaching plan. Our approach connects positioning, application quality and consistent action. We support students, graduates, experienced professionals and career changers, including people targeting French-speaking markets.</p><Link href="/en/coaching" className={`${primaryButton} mt-6`}>Explore coaching</Link></section>
    <section><h2 className="text-3xl font-black">A straightforward way forward</h2><ol className="mt-7 grid gap-6 md:grid-cols-3">{[['01', 'Start with your priorities', 'Identify what is slowing you down: direction, application quality or organisation.'], ['02', 'Choose the right support', 'Use a focused tool or discuss a coaching plan before committing.'], ['03', 'Put it into practice', 'Work through clear next actions and adjust as your search develops.']].map(([number, title, copy]) => <li key={number}><p className="text-sm font-bold text-[#0683C9]">{number}</p><h3 className="mt-3 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{copy}</p></li>)}</ol><p className="mt-7 text-sm text-slate-500">No service or template can guarantee an interview, job offer or immigration outcome.</p></section>
    <section><h2 className="text-3xl font-black">Build your knowledge, too.</h2><p className="mt-4 leading-7 text-slate-600">Explore practical guidance for resumes, interviews and a more structured search.</p><Link href="/en/resources" className={`${primaryButton} mt-5`}>Browse resources</Link></section>
    <section id="contact"><EnglishLeadForm /><p className="mt-5 text-sm text-slate-500">Prefer email? <a href="mailto:talentiques@gmail.com" className="text-[#0683C9] underline">talentiques@gmail.com</a></p></section>
  </EnglishPage>;
}
