'use client';

import { Pencil, Plus, UserPlus, X } from 'lucide-react';
import { useState } from 'react';
import type { Campaign } from '@/lib/acquisition/types';
import { useAcquisition } from './AcquisitionProvider';
import { EmptyState, MetricCard, Panel, StatusBadge } from './ui';

export function CampaignsView() {
  const { campaigns, prospects, markets, catalogItems, saveCampaign, updateProspect, saving } = useAcquisition();
  const [editing, setEditing] = useState<Campaign | null>(null);
  const [members, setMembers] = useState<Campaign | null>(null);
  const activeMarkets = markets.filter((item) => item.active);
  const activeCatalog = catalogItems.filter((item) => item.active);
  const newCampaign = (): Campaign => ({ id: `new-${crypto.randomUUID()}`, name: '', marketId: activeMarkets[0]?.id ?? '', marketName: activeMarkets[0]?.name ?? '', language: activeMarkets[0]?.language ?? 'FR', catalogItemId: '', audience: '', status: 'Active', product: '', revenue: 0, currency: activeMarkets[0]?.defaultCurrency ?? 'EUR' });

  return <>
    <div className="mb-5 flex justify-end"><button onClick={() => setEditing(newCampaign())} disabled={!activeMarkets.length} className="inline-flex items-center gap-2 rounded-xl bg-[#0683C9] px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus size={17} />Nouvelle campagne</button></div>
    {!campaigns.length ? <EmptyState title="Aucune campagne" detail="Créez une campagne liée à un marché et, si utile, à une offre du catalogue." /> : <div className="space-y-6">{campaigns.map((campaign) => {
      const rows = prospects.filter((item) => item.campaignId === campaign.id); const contact = rows.filter((item) => !['Nouveau','À qualifier','À contacter'].includes(item.status)).length; const replies = rows.filter((item) => ['A répondu','Intéressé','Offre envoyée','Client'].includes(item.status)).length; const interested = rows.filter((item) => ['Intéressé','Offre envoyée','Client'].includes(item.status)).length; const offers = rows.filter((item) => ['Offre envoyée','Client'].includes(item.status)).length; const sales = rows.filter((item) => item.status === 'Client').length;
      return <Panel key={campaign.id} title={campaign.name} eyebrow={`${campaign.marketName} · ${campaign.product || 'Sans offre liée'}`} action={<div className="flex items-center gap-2"><StatusBadge value={campaign.status} /><button onClick={() => setMembers(campaign)} className="rounded-lg border border-slate-200 p-2" aria-label="Gérer les prospects"><UserPlus size={16} /></button><button onClick={() => setEditing(campaign)} className="rounded-lg border border-slate-200 p-2" aria-label="Modifier"><Pencil size={16} /></button></div>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5 xl:grid-cols-9"><MetricCard label="Prospects" value={rows.length} /><MetricCard label="Contactés" value={contact} /><MetricCard label="Réponses" value={replies} /><MetricCard label="Intéressés" value={interested} /><MetricCard label="Offres" value={offers} /><MetricCard label="Ventes" value={sales} /><MetricCard label="CA" value={`${campaign.revenue.toLocaleString('fr-FR')} ${campaign.currency}`} /><MetricCard label="Taux réponse" value={`${contact ? Math.round(replies / contact * 100) : 0}%`} /><MetricCard label="Conversion" value={`${contact ? Math.round(sales / contact * 100) : 0}%`} /></div></Panel>;
    })}</div>}
    {editing ? <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={(event) => { event.preventDefault(); void saveCampaign(editing).then(() => setEditing(null)); }} className="w-full max-w-xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="font-heading text-2xl font-bold">{editing.id.startsWith('new-') ? 'Nouvelle campagne' : 'Modifier la campagne'}</h2><button type="button" onClick={() => setEditing(null)}><X /></button></div><label className="mt-6 block"><span className="mb-2 block text-sm font-bold">Nom de campagne</span><input className="input" value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} required /></label><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">Marché</span><select className="input" value={editing.marketId} onChange={(event) => { const market = activeMarkets.find((item) => item.id === event.target.value); if (market) setEditing({ ...editing, marketId: market.id, marketName: market.name, language: market.language, currency: market.defaultCurrency }); }} required><option value="">Sélectionner</option>{activeMarkets.map((market) => <option key={market.id} value={market.id}>{market.name}</option>)}</select></label><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">Offre du catalogue</span><select className="input" value={editing.catalogItemId ?? ''} onChange={(event) => { const item = activeCatalog.find((entry) => entry.id === event.target.value); setEditing({ ...editing, catalogItemId: event.target.value, product: item?.name ?? '' }); }}><option value="">Aucune offre</option>{activeCatalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">Audience</span><input className="input" value={editing.audience ?? ''} onChange={(event) => setEditing({ ...editing, audience: event.target.value })} /></label><div className="mt-4 grid grid-cols-2 gap-4"><label><span className="mb-2 block text-sm font-bold">Statut</span><select className="input" value={editing.status} onChange={(event) => setEditing({ ...editing, status: event.target.value as Campaign['status'] })}><option>Active</option><option>En pause</option><option>Terminée</option></select></label><label><span className="mb-2 block text-sm font-bold">Devise</span><select className="input" value={editing.currency} onChange={(event) => setEditing({ ...editing, currency: event.target.value as Campaign['currency'] })}><option>EUR</option><option>USD</option></select></label></div><button disabled={saving || !editing.marketId} className="mt-6 rounded-xl bg-[#0683C9] px-5 py-3 font-bold text-white disabled:opacity-50">Enregistrer</button></form></div> : null}
    {members ? <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-[#0683C9]">{members.name}</p><h2 className="mt-2 font-heading text-2xl font-bold">Prospects de la campagne</h2></div><button onClick={() => setMembers(null)}><X /></button></div><div className="mt-6 space-y-2">{prospects.map((prospect) => { const checked = prospect.campaignId === members.id; return <label key={prospect.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={checked} onChange={() => void updateProspect(prospect.id, { campaignId: checked ? '' : members.id }, { type: 'status', label: checked ? 'Retiré de la campagne' : 'Ajouté à la campagne', detail: members.name })} /><span className="flex-1 font-semibold">{prospect.firstName} {prospect.lastName}</span><span className="text-xs text-slate-500">{prospect.status}</span></label>; })}</div></div></div> : null}
  </>;
}
