'use client';

import Link from 'next/link';
import { Archive, ArrowLeft, CalendarClock, Clipboard, ExternalLink, Mail, MessageCircle, NotebookPen, Pencil, Save, X } from 'lucide-react';
import { useState } from 'react';
import { prospectStatuses, type Prospect } from '@/lib/acquisition/types';
import { recordStatusChange, useProspect } from './AcquisitionProvider';
import { formatShortDate, Panel, Score, StatusBadge } from './ui';

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return <div><dt className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 break-words text-sm font-semibold text-slate-800">{value || '—'}</dd></div>;
}

export function ProspectDetailView({ id }: { id: string }) {
  const { prospect, addNote, updateProspect, archiveProspect, templates, saving } = useProspect(id);
  const [note, setNote] = useState('');
  const [copied, setCopied] = useState(false);
  const [draft, setDraft] = useState<Partial<Prospect> | null>(null);
  if (!prospect) return <Panel title="Prospect introuvable"><p className="text-slate-600">Ce prospect n’existe pas dans la base locale.</p><Link href="/acquisition/prospects" className="mt-5 inline-flex font-bold text-[#0683C9]">Retour aux prospects</Link></Panel>;
  const template = templates.find((item) => item.language === prospect.language && item.channel === 'LinkedIn') ?? templates[0];
  const message = (template?.body ?? `Bonjour ${prospect.firstName}, votre parcours a retenu mon attention.`).replaceAll('{{prénom}}', prospect.firstName).replaceAll('{{first_name}}', prospect.firstName).replaceAll('{{entreprise}}', prospect.company).replaceAll('{{company}}', prospect.company);
  async function copyMessage() { await navigator.clipboard.writeText(message); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  function schedule() {
    const date = new Date(); date.setDate(date.getDate() + 2); date.setHours(10, 0, 0, 0);
    updateProspect(id, { nextAction: 'Relancer le prospect', nextActionAt: date.toISOString(), nextActionType: 'Relance', taskStatus: 'À faire' }, { type: 'follow_up', label: 'Relance planifiée', detail: formatShortDate(date.toISOString()) });
  }
  return <>
    <Link href="/acquisition/prospects" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-[#0683C9]"><ArrowLeft size={17} />Retour aux prospects</Link>
    <div className="mb-7 flex flex-col gap-5 rounded-3xl border border-slate-200 bg-white p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#071b2b] font-heading text-xl font-bold text-white">{prospect.firstName[0]}{prospect.lastName[0]}</span><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-heading text-2xl font-bold sm:text-3xl">{prospect.firstName} {prospect.lastName}</h2><StatusBadge value={prospect.status} /></div><p className="mt-1 text-slate-600">{prospect.jobTitle} · {prospect.company}</p><p className="mt-1 text-sm text-slate-400">{prospect.city}, {prospect.country} · {prospect.market}</p></div></div><Score value={prospect.score} /></div>
    <div className="mb-7 flex flex-wrap gap-2"><a href={prospect.linkedinUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#0683C9] px-4 py-3 text-sm font-bold text-white"><ExternalLink size={16} />Ouvrir LinkedIn</a><button onClick={() => void copyMessage()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><Clipboard size={16} />{copied ? 'Copié !' : 'Copier un message'}</button>{prospect.whatsapp ? <a onClick={() => void updateProspect(id, {}, { type: 'follow_up', label: 'WhatsApp ouvert' })} href={`https://wa.me/${prospect.whatsapp.replace(/\D/g, '')}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><MessageCircle size={16} />Ouvrir WhatsApp</a> : null}<button disabled title="Disponible lors de la connexion Gmail" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold opacity-50"><Mail size={16} />Envoyer email</button><button onClick={schedule} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><CalendarClock size={16} />Planifier une relance</button><button onClick={() => setDraft(prospect)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"><Pencil size={16} />Modifier</button><button onClick={() => { if (window.confirm('Archiver ce prospect ?')) void archiveProspect(id).then(() => window.location.assign('/acquisition/prospects')); }} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 bg-white px-4 py-3 text-sm font-bold text-rose-700"><Archive size={16} />Archiver</button></div>
    <div className="grid gap-7 xl:grid-cols-2">
      <Panel title="Identité"><dl className="grid gap-5 sm:grid-cols-2"><Field label="Prénom" value={prospect.firstName} /><Field label="Nom" value={prospect.lastName} /><Field label="Pays" value={prospect.country} /><Field label="Ville" value={prospect.city} /><Field label="Langue" value={prospect.language} /><Field label="Poste" value={prospect.jobTitle} /><Field label="Entreprise" value={prospect.company} /><Field label="LinkedIn" value={<a className="text-[#0683C9]" href={prospect.linkedinUrl} target="_blank" rel="noreferrer">Voir le profil</a>} /></dl></Panel>
      <Panel title="Coordonnées"><dl className="grid gap-5 sm:grid-cols-2"><Field label="Email" value={prospect.email} /><Field label="Téléphone" value={prospect.phone} /><Field label="WhatsApp" value={prospect.whatsapp} /><Field label="Vérification" value={<StatusBadge value={prospect.verificationStatus} />} /><Field label="Source de la donnée" value={prospect.dataSource} /><Field label="Source d’acquisition" value={prospect.source} /></dl></Panel>
      <Panel title="Qualification"><dl className="grid gap-5 sm:grid-cols-2"><Field label="Score /100" value={<Score value={prospect.score} />} /><Field label="Segment" value={prospect.segment} /><Field label="Marché" value={prospect.market} /><Field label="Recherche active" value={prospect.activeSearch ? 'Oui' : 'Non'} /><Field label="Produit potentiel" value={prospect.potentialProduct} /><Field label="Tags" value={<div className="flex flex-wrap gap-1">{prospect.tags.map((tag) => <span key={tag} className="rounded-full bg-slate-100 px-2 py-1 text-xs">{tag}</span>)}</div>} /></dl></Panel>
      <Panel title="CRM"><dl className="grid gap-5 sm:grid-cols-2"><Field label="Statut" value={<select value={prospect.status} onChange={(event) => { const next = event.target.value as typeof prospect.status; updateProspect(id, { status: next }, recordStatusChange(next)); }} className="rounded-lg border border-slate-200 bg-white px-3 py-2">{prospectStatuses.map((status) => <option key={status}>{status}</option>)}</select>} /><Field label="Dernière action" value={prospect.lastAction} /><Field label="Prochaine action" value={prospect.nextAction} /><Field label="Date / heure" value={formatShortDate(prospect.nextActionAt)} /><Field label="Type d’action" value={prospect.nextActionType} /><Field label="Statut de tâche" value={prospect.taskStatus} /><Field label="Propriétaire" value={prospect.owner} /><Field label="Notes" value={prospect.notes} /></dl></Panel>
      <Panel title="Historique" className="xl:col-span-2"><ol className="relative ml-2 border-l border-slate-200 pl-6">{[...prospect.activities].sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)).map((event) => <li key={event.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[29px] top-1 h-2.5 w-2.5 rounded-full bg-[#0683C9] ring-4 ring-white" /><p className="text-sm font-bold">{event.label}</p>{event.detail ? <p className="mt-1 text-sm text-slate-500">{event.detail}</p> : null}<time className="mt-1 block text-xs text-slate-400">{formatShortDate(event.occurredAt)}</time></li>)}</ol></Panel>
      <Panel title="Ajouter une note" className="xl:col-span-2"><div className="flex flex-col gap-3 sm:flex-row"><textarea className="input flex-1" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Note privée sur le prospect…" /><button onClick={() => { if (!note.trim()) return; void addNote(id, note.trim()).then((ok) => { if (ok) setNote(''); }); }} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-[#0683C9] px-5 font-bold text-white"><NotebookPen size={17} />Ajouter</button></div></Panel>
    </div>
    {draft ? <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={(event) => { event.preventDefault(); void updateProspect(id, draft, { type: 'status', label: 'Fiche prospect mise à jour' }).then((ok) => { if (ok) setDraft(null); }); }} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="font-heading text-2xl font-bold">Modifier le prospect</h2><button type="button" onClick={() => setDraft(null)}><X /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{([['firstName','Prénom'],['lastName','Nom'],['country','Pays'],['city','Ville'],['jobTitle','Poste'],['company','Entreprise'],['email','Email'],['phone','Téléphone'],['whatsapp','WhatsApp'],['linkedinUrl','LinkedIn'],['segment','Segment'],['potentialProduct','Produit']] as const).map(([key,label]) => <label key={key}><span className="mb-2 block text-sm font-bold">{label}</span><input className="input" value={String(draft[key] ?? '')} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} /></label>)}<label><span className="mb-2 block text-sm font-bold">Score /100</span><input type="number" min="0" max="100" className="input" value={draft.score ?? 0} onChange={(event) => setDraft({ ...draft, score: Number(event.target.value) })} /></label><label><span className="mb-2 block text-sm font-bold">Statut</span><select className="input" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as typeof prospect.status })}>{prospectStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Notes</span><textarea className="input" value={draft.notes ?? ''} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} /></label></div><button disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#0683C9] px-5 py-3 font-bold text-white disabled:opacity-50"><Save size={17} />Enregistrer</button></form></div> : null}
  </>;
}
