'use client';

import { Check, ChevronRight, Clipboard, Clock3, ExternalLink, Mail, MapPin, Phone, SearchCheck, ThumbsDown, ThumbsUp } from 'lucide-react';
import { useMemo, useState } from 'react';
import { recordStatusChange, useAcquisition } from './AcquisitionProvider';
import { Score, StatusBadge } from './ui';
import { sortProspectingQueue } from '@/lib/acquisition/automation-engine';

export function ProspectingView() {
  const { prospects, templates, updateProspect, saving, error } = useAcquisition();
  const queue = useMemo(() => sortProspectingQueue(prospects), [prospects]);
  const [index, setIndex] = useState(0); const [copied, setCopied] = useState(false);
  const prospect = queue[index % Math.max(queue.length, 1)];
  if (!prospect) return <div className="rounded-3xl border border-slate-200 bg-white p-10 text-center"><SearchCheck className="mx-auto text-[#0683C9]" /><h2 className="mt-4 font-heading text-2xl font-bold">File terminée</h2><p className="mt-2 text-slate-500">Tous les prospects actifs ont été traités.</p></div>;
  const template = templates.find((item) => item.active !== false && item.language === prospect.language && item.channel === 'LinkedIn') ?? templates.find((item) => item.active !== false);
  const message = (template?.body ?? `Bonjour ${prospect.firstName}, votre parcours a retenu mon attention.`).replaceAll('{{prénom}}', prospect.firstName).replaceAll('{{first_name}}', prospect.firstName).replaceAll('{{entreprise}}', prospect.company).replaceAll('{{company}}', prospect.company);
  function next() { setIndex((current) => (current + 1) % queue.length); setCopied(false); }
  async function act(status: typeof prospect.status, label: string, detail: string) { if (await updateProspect(prospect.id, { status, lastAction: label }, { ...recordStatusChange(status), detail })) next(); }
  async function later() { const date = new Date(); date.setDate(date.getDate() + 7); if (await updateProspect(prospect.id, { status: 'Relance', nextAction: 'Reprendre contact', nextActionAt: date.toISOString(), nextActionType: 'Relance', taskStatus: 'À faire' }, { type: 'follow_up', label: 'Reporté à plus tard' })) next(); }
  async function copy() { await navigator.clipboard.writeText(message); setCopied(true); }
  return <>{error ? <p className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800">{error}</p> : null}<div className="grid gap-7 xl:grid-cols-[.95fr_1.05fr]">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0683C9]">Prospect {index + 1} / {queue.length}</p><Score value={prospect.score} /></div><div className="mt-8 flex items-center gap-4"><span className="flex h-20 w-20 items-center justify-center rounded-3xl bg-[#071b2b] font-heading text-2xl font-bold text-white">{prospect.firstName[0]}{prospect.lastName[0]}</span><div><h2 className="font-heading text-3xl font-bold">{prospect.firstName} {prospect.lastName}</h2><p className="mt-1 text-slate-600">{prospect.jobTitle} · {prospect.company}</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{[[MapPin,'Marché',`${prospect.city}, ${prospect.country}`],[Mail,'Email',prospect.email],[Phone,'Téléphone',prospect.phone || 'Non renseigné'],[SearchCheck,'Recherche active',prospect.activeSearch ? 'Oui' : 'Non']].map(([Icon,label,value]) => { const C = Icon as typeof MapPin; return <div key={String(label)} className="rounded-2xl bg-slate-50 p-4"><C size={17} className="text-[#0683C9]" /><p className="mt-3 text-xs font-bold uppercase text-slate-400">{String(label)}</p><p className="mt-1 break-words text-sm font-semibold">{String(value)}</p></div>; })}</div><div className="mt-6 flex flex-wrap gap-2"><StatusBadge value={prospect.status} /><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{prospect.source}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{prospect.potentialProduct}</span></div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0683C9]">Message suggéré</p><h2 className="mt-3 font-heading text-2xl font-bold">{template?.name ?? 'Message personnalisé'}</h2><div className="mt-6 rounded-2xl border border-sky-100 bg-sky-50/60 p-5 text-sm leading-7 text-slate-700">{message}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={saving} onClick={() => void copy()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 font-bold"><Clipboard size={17} />{copied ? 'Message copié' : 'Copier'}</button><a href={prospect.linkedinUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#0683C9] font-bold text-white"><ExternalLink size={17} />Ouvrir LinkedIn</a><button disabled={saving} onClick={() => void act('Contacté','Message LinkedIn envoyé','Contact manuel enregistré depuis Prospecting Mode.')} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#071b2b] font-bold text-white disabled:opacity-50"><Check size={17} />Message envoyé</button><button disabled={saving} onClick={() => void act('Intéressé','Prospect intéressé','Intérêt enregistré depuis Prospecting Mode.')} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-600 font-bold text-white disabled:opacity-50"><ThumbsUp size={17} />Intéressé</button><button disabled={saving} onClick={() => void act('Perdu','Pas intéressé','Réponse négative enregistrée.')} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 font-bold disabled:opacity-50"><ThumbsDown size={17} />Pas intéressé</button><button disabled={saving} onClick={() => void later()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 font-bold disabled:opacity-50"><Clock3 size={17} />Plus tard</button><button onClick={next} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 font-bold">Skip</button><button onClick={next} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-100 font-bold">Suivant <ChevronRight size={17} /></button></div></section>
  </div></>;
}
