'use client';

import Link from 'next/link';
import { Archive, ChevronLeft, ChevronRight, Download, Plus, Search, Upload, X } from 'lucide-react';
import { useDeferredValue, useMemo, useState } from 'react';
import { csvFields, mapCsvRows, parseCsv } from '@/lib/acquisition/csv';
import { prospectStatuses, type Prospect } from '@/lib/acquisition/types';
import type { DuplicateMatch } from '@/lib/acquisition/dedupe';
import { useAcquisition } from './AcquisitionProvider';
import { EmptyState, formatShortDate, Score, StatusBadge } from './ui';

const labels: Record<string, string> = { first_name: 'Prénom', last_name: 'Nom', linkedin_url: 'LinkedIn', email: 'Email', phone: 'Téléphone', country: 'Pays', city: 'Ville', language: 'Langue', job_title: 'Poste', company: 'Entreprise', source: 'Source', campaign: 'Campagne' };

export function ProspectsView() {
  const store = useAcquisition();
  const { prospects, markets, campaigns, addProspect, archiveProspect, importCsv, saving, error, clearError } = store;
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [market, setMarket] = useState('');
  const [sort, setSort] = useState('updated'); const [page, setPage] = useState(1); const [creating, setCreating] = useState(false);
  const [pendingProspect, setPendingProspect] = useState<Prospect | null>(null); const [duplicates, setDuplicates] = useState<DuplicateMatch[]>([]);
  const [csv, setCsv] = useState<{ headers: string[]; rows: string[][]; mapping: Record<string, string> } | null>(null);
  const [report, setReport] = useState<{ imported: number; duplicates: number; skipped: number; errors: Array<{ row: number; message: string }> } | null>(null);
  const deferredQuery = useDeferredValue(query);
  const filtered = useMemo(() => prospects.filter((item) => { const haystack = `${item.firstName} ${item.lastName} ${item.company} ${item.jobTitle} ${item.city}`.toLowerCase(); return (!deferredQuery || haystack.includes(deferredQuery.toLowerCase())) && (!status || item.status === status) && (!market || item.market === market); }).sort((a, b) => sort === 'score' ? b.score - a.score : sort === 'name' ? `${a.lastName}${a.firstName}`.localeCompare(`${b.lastName}${b.firstName}`) : sort === 'next' ? (a.nextActionAt || 'z').localeCompare(b.nextActionAt || 'z') : b.updatedAt.localeCompare(a.updatedAt)), [prospects, deferredQuery, status, market, sort]);
  const pageSize = 25; const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const shown = filtered.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);

  async function submitProspect(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); clearError(); const form = new FormData(event.currentTarget); const now = new Date().toISOString(); const selectedMarket = markets.find((item) => item.id === String(form.get('marketId'))) ?? markets.find((item) => item.name === String(form.get('market'))); if (!selectedMarket) return; const campaign = campaigns.find((item) => (item.id === String(form.get('campaignId')) || item.name === String(form.get('market'))) && item.marketId === selectedMarket.id);
    const prospect: Prospect = { id: crypto.randomUUID(), firstName: String(form.get('firstName')).trim(), lastName: String(form.get('lastName')).trim(), country: String(form.get('country')).trim(), city: String(form.get('city')).trim(), language: String(form.get('language')) as 'FR' | 'EN', jobTitle: String(form.get('jobTitle')).trim(), company: String(form.get('company')).trim(), linkedinUrl: String(form.get('linkedinUrl')).trim(), email: String(form.get('email')).trim(), phone: String(form.get('phone')).trim(), whatsapp: '', verificationStatus: 'À vérifier', dataSource: 'Saisie manuelle', source: 'Manuel', linkedinRelation: 'Hors réseau', score: Number(form.get('score')) || 50, segment: 'À qualifier', marketId: selectedMarket.id, market: selectedMarket.name, activeSearch: false, potentialProduct: String(form.get('product')).trim() || 'À définir', tags: [], status: 'Nouveau', lastAction: 'Prospect créé', nextAction: 'Qualifier le prospect', nextActionAt: now, nextActionType: 'Qualification', taskStatus: 'À faire', owner: 'Othmane', notes: '', campaignId: campaign?.id ?? '', createdAt: now, updatedAt: now, activities: [] };
    const result = await addProspect(prospect).catch(() => null); if (!result) return;
    if (result.duplicate) { setPendingProspect(prospect); setDuplicates(result.duplicate); } else setCreating(false);
  }

  async function loadCsv(file: File) { const parsed = parseCsv(await file.text()); const mapping = Object.fromEntries(parsed.headers.map((header) => [header, csvFields.includes(header.toLowerCase() as typeof csvFields[number]) ? header.toLowerCase() : ''])); setCsv({ ...parsed, mapping }); setReport(null); }
  async function runImport(forceDuplicates = false) { if (!csv) return; const rows = mapCsvRows(csv.headers, csv.rows, csv.mapping); setReport(await importCsv(rows, forceDuplicates).catch(() => ({ imported: 0, duplicates: 0, skipped: 0, errors: [{ row: 0, message: 'Import impossible' }] }))); }
  const exportHref = `/api/acquisition/export?${new URLSearchParams({ ...(query ? { q: query } : {}), ...(status ? { status } : {}), ...(market ? { market } : {}) })}`;

  return <>
    {error ? <div className="mb-5 flex items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800"><span>{error}</span><button onClick={clearError} aria-label="Fermer"><X size={17} /></button></div> : null}
    <div className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 lg:grid-cols-[1fr_170px_170px_150px_auto_auto_auto]">
      <label className="relative"><span className="sr-only">Rechercher</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} className="input pl-11" placeholder="Nom, entreprise, poste ou ville…" /></label>
      <select className="input" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} aria-label="Statut"><option value="">Tous statuts</option>{prospectStatuses.map((item) => <option key={item}>{item}</option>)}</select>
      <select className="input" value={market} onChange={(event) => { setMarket(event.target.value); setPage(1); }} aria-label="Marché"><option value="">Tous marchés</option>{markets.map((item) => <option key={item.id}>{item.name}</option>)}</select>
      <select className="input" value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Tri"><option value="updated">Plus récents</option><option value="score">Score décroissant</option><option value="name">Nom</option><option value="next">Prochaine action</option></select>
      <button onClick={() => setCreating(true)} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-[#0683C9] px-4 text-sm font-bold text-white"><Plus size={17} />Ajouter</button>
      <label className="inline-flex min-h-14 cursor-pointer items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold"><Upload size={17} />Importer<input type="file" accept=".csv,text/csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void loadCsv(file); }} /></label>
      <a href={exportHref} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold"><Download size={17} />Exporter</a>
    </div>
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[1320px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr>{['Nom','Pays / ville','Langue','Poste / entreprise','Source','Relation','Score','Statut','Produit','Dernière action','Prochaine action','Actions'].map((header) => <th key={header} className="px-4 py-3 font-bold">{header}</th>)}</tr></thead><tbody>{shown.map((item) => <tr key={item.id} className="border-t border-slate-100 transition hover:bg-sky-50/30"><td className="px-4 py-4"><Link href={`/acquisition/prospects/${item.id}`} className="font-bold text-[#0683C9]">{item.firstName} {item.lastName}</Link></td><td className="px-4"><strong>{item.country}</strong><span className="block text-xs text-slate-500">{item.city}</span></td><td className="px-4">{item.language}</td><td className="max-w-[220px] px-4"><span className="block truncate font-semibold">{item.jobTitle}</span><span className="block truncate text-xs text-slate-500">{item.company}</span></td><td className="px-4">{item.source}</td><td className="px-4">{item.linkedinRelation}</td><td className="px-4"><Score value={item.score} /></td><td className="px-4"><StatusBadge value={item.status} /></td><td className="max-w-[180px] px-4"><span className="block truncate">{item.potentialProduct}</span></td><td className="max-w-[180px] px-4"><span className="block truncate">{item.lastAction}</span></td><td className="max-w-[220px] px-4"><span className="block truncate font-semibold">{item.nextAction}</span><span className="block text-xs text-slate-500">{formatShortDate(item.nextActionAt)}</span></td><td className="px-4"><div className="flex gap-1"><Link href={`/acquisition/prospects/${item.id}`} aria-label={`Ouvrir ${item.firstName}`} className="rounded-lg p-2 text-slate-400 hover:text-[#0683C9]"><ChevronRight size={18} /></Link><button onClick={() => { if (window.confirm(`Archiver ${item.firstName} ${item.lastName} ?`)) void archiveProspect(item.id); }} className="rounded-lg p-2 text-slate-400 hover:text-rose-600" aria-label={`Archiver ${item.firstName}`}><Archive size={17} /></button></div></td></tr>)}</tbody></table>{!shown.length ? <div className="p-6"><EmptyState title="Aucun prospect trouvé" detail="Modifiez les filtres ou ajoutez un premier prospect." /></div> : null}</div>
    <div className="mt-4 flex items-center justify-between text-sm text-slate-500"><p>{filtered.length} résultat(s) · page {Math.min(page, pages)} / {pages}</p><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-slate-200 bg-white p-2 disabled:opacity-40" aria-label="Page précédente"><ChevronLeft size={17} /></button><button disabled={page >= pages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-slate-200 bg-white p-2 disabled:opacity-40" aria-label="Page suivante"><ChevronRight size={17} /></button></div></div>

    {creating ? <div className="fixed inset-0 z-[60] flex items-end justify-center bg-slate-950/50 p-4 sm:items-center"><form onSubmit={(event) => void submitProspect(event)} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0683C9]">Nouveau prospect</p><h2 className="mt-2 font-heading text-2xl font-bold">Ajouter à la base Supabase</h2></div><button type="button" onClick={() => setCreating(false)} className="rounded-lg p-2" aria-label="Fermer"><X /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['firstName','Prénom','text'],['lastName','Nom','text'],['country','Pays','text'],['city','Ville','text'],['jobTitle','Poste','text'],['company','Entreprise','text'],['email','Email','email'],['phone','Téléphone','tel'],['linkedinUrl','URL LinkedIn','url'],['product','Produit potentiel','text'],['score','Score /100','number']].map(([name,label,type]) => <label key={name} className={name === 'linkedinUrl' ? 'sm:col-span-2' : ''}><span className="mb-2 block text-sm font-bold">{label}</span><input className="input" name={name} type={type} min={name === 'score' ? 0 : undefined} max={name === 'score' ? 100 : undefined} defaultValue={name === 'score' ? 50 : undefined} required={['firstName','lastName','country','city','jobTitle','company'].includes(name)} /></label>)}<label><span className="mb-2 block text-sm font-bold">Langue</span><select name="language" className="input"><option>FR</option><option>EN</option></select></label><label><span className="mb-2 block text-sm font-bold">Marché</span><select name="market" className="input">{campaigns.map((item) => <option key={item.id}>{item.name}</option>)}</select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setCreating(false)} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Annuler</button><button disabled={saving} className="rounded-xl bg-[#0683C9] px-5 py-3 font-bold text-white disabled:opacity-50">{saving ? 'Enregistrement…' : 'Créer le prospect'}</button></div></form></div> : null}

    {duplicates.length && pendingProspect ? <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-2xl rounded-3xl bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-600">Doublon potentiel détecté</p><h2 className="mt-2 font-heading text-2xl font-bold">Vérifiez avant de créer</h2><div className="mt-5 space-y-3">{duplicates.map(({ prospect, fields }) => <div key={prospect.id} className="rounded-2xl bg-amber-50 p-4"><p className="font-bold">{prospect.firstName} {prospect.lastName} · {prospect.company}</p><p className="mt-1 text-sm text-amber-800">Correspondance : {fields.join(', ')}</p></div>)}</div><div className="mt-6 flex flex-wrap justify-end gap-3"><button onClick={() => { setDuplicates([]); setPendingProspect(null); }} className="rounded-xl border border-slate-200 px-4 py-3 font-bold">Annuler</button><button onClick={() => void addProspect(pendingProspect, { force: true }).then(() => { setDuplicates([]); setPendingProspect(null); setCreating(false); })} className="rounded-xl border border-amber-300 px-4 py-3 font-bold text-amber-800">Créer quand même</button><button onClick={() => void addProspect(pendingProspect, { mergeId: duplicates[0].prospect.id }).then(() => { setDuplicates([]); setPendingProspect(null); setCreating(false); })} className="rounded-xl bg-[#0683C9] px-4 py-3 font-bold text-white">Fusionner</button></div></div></div> : null}

    {csv ? <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0683C9]">Import CSV</p><h2 className="mt-2 font-heading text-2xl font-bold">Mapping et validation</h2></div><button onClick={() => setCsv(null)} aria-label="Fermer"><X /></button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{csv.headers.map((header) => <label key={header}><span className="mb-1 block truncate text-xs font-bold text-slate-500">Colonne « {header} »</span><select className="input" value={csv.mapping[header] ?? ''} onChange={(event) => setCsv({ ...csv, mapping: { ...csv.mapping, [header]: event.target.value } })}><option value="">Ignorer</option>{csvFields.map((field) => <option key={field} value={field}>{labels[field]}</option>)}</select></label>)}</div><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50"><tr>{csv.headers.map((header) => <th key={header} className="px-3 py-2">{header}</th>)}</tr></thead><tbody>{csv.rows.slice(0, 8).map((row, index) => <tr key={index} className="border-t border-slate-100">{csv.headers.map((header, column) => <td key={header} className="max-w-48 truncate px-3 py-2">{row[column]}</td>)}</tr>)}</tbody></table></div><p className="mt-3 text-sm text-slate-500">Aperçu de {Math.min(8, csv.rows.length)} ligne(s) sur {csv.rows.length}. Les lignes invalides ne seront jamais importées silencieusement.</p>{report ? <div className="mt-5 grid gap-3 sm:grid-cols-4"><StatusBadge value={`${report.imported} importés`} /><StatusBadge value={`${report.duplicates} doublons`} /><StatusBadge value={`${report.skipped} ignorés`} /><StatusBadge value={`${report.errors.length} erreurs`} />{report.errors.length ? <div className="sm:col-span-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{report.errors.slice(0, 10).map((item) => <p key={`${item.row}-${item.message}`}>Ligne {item.row} : {item.message}</p>)}</div> : null}</div> : null}<div className="mt-6 flex flex-wrap justify-end gap-3"><button onClick={() => setCsv(null)} className="rounded-xl border border-slate-200 px-5 py-3 font-bold">Fermer</button>{report?.duplicates ? <button onClick={() => void runImport(true)} className="rounded-xl border border-amber-300 px-5 py-3 font-bold text-amber-800">Importer aussi les doublons</button> : null}<button disabled={saving || !csv.mapping.first_name && !Object.values(csv.mapping).includes('first_name')} onClick={() => void runImport(false)} className="rounded-xl bg-[#0683C9] px-5 py-3 font-bold text-white disabled:opacity-50">{saving ? 'Import…' : 'Valider l’import'}</button></div></div></div> : null}
  </>;
}
